name: vishal_saini
description: "Vishal Saini Advocate"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.10.13
  webview_flutter_wkwebview: ^3.19.1
  connectivity_plus: ^7.0.0
  url_launcher: ^6.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/adv_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1B3A6B"  # your navy blue color
  adaptive_icon_foreground: "assets/images/adv_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/adv_logo.png